import { type Driver, type TopDriver } from './types';

export const topDrivers: TopDriver[] = [
  {
    id: '2',
    rank: 2,
    initials: 'MC',
    name: 'Michael Chen',
    tier: 'Gold',
    points: 5180,
  },
  {
    id: '1',
    rank: 1,
    initials: 'SM',
    name: 'Sarah Martinez',
    tier: 'Gold',
    points: 5420,
  },
  {
    id: '3',
    rank: 3,
    initials: 'ER',
    name: 'Emily Rodriguez',
    tier: 'Silver',
    points: 4950,
  },
];

export const allDrivers: Driver[] = [
  {
    id: '4',
    rank: 4,
    initials: 'JW',
    name: 'James Wilson',
    tier: 'Gold',
    orders: 275,
    points: 4720,
    trend: 'stable',
  },
  {
    id: '5',
    rank: 5,
    initials: 'LA',
    name: 'Lisa Anderson',
    tier: 'Gold',
    orders: 268,
    points: 4590,
    trend: 'up',
  },
  {
    id: '6',
    rank: 6,
    initials: 'DT',
    name: 'David Thompson',
    tier: 'Silver',
    orders: 252,
    points: 4320,
    trend: 'up',
  },
  {
    id: '7',
    rank: 7,
    initials: 'JL',
    name: 'Jennifer Lee',
    tier: 'Silver',
    orders: 245,
    points: 4180,
    trend: 'down',
  },
  {
    id: '8',
    rank: 8,
    initials: 'RG',
    name: 'Robert Garcia',
    tier: 'Silver',
    orders: 238,
    points: 3950,
    trend: 'stable',
  },
  {
    id: '9',
    rank: 9,
    initials: 'AT',
    name: 'Amanda Taylor',
    tier: 'Silver',
    orders: 227,
    points: 3720,
    trend: 'up',
  },
  {
    id: '10',
    rank: 10,
    initials: 'CM',
    name: 'Christopher Moore',
    tier: 'Silver',
    orders: 219,
    points: 3580,
    trend: 'up',
  },
  {
    id: '11',
    rank: 11,
    initials: 'JW2',
    name: 'Jessica White',
    tier: 'Silver',
    orders: 208,
    points: 3340,
    trend: 'down',
  },
  {
    id: '12',
    rank: 12,
    initials: 'JD',
    name: 'John Driver',
    tier: 'Silver',
    orders: 234,
    points: 2450,
    trend: 'up',
    isCurrentUser: true,
  },
  {
    id: '13',
    rank: 13,
    initials: 'DH',
    name: 'Daniel Harris',
    tier: 'Bronze',
    orders: 189,
    points: 2280,
    trend: 'stable',
  },
  {
    id: '14',
    rank: 14,
    initials: 'MC2',
    name: 'Michelle Clark',
    tier: 'Bronze',
    orders: 178,
    points: 2150,
    trend: 'up',
  },
  {
    id: '15',
    rank: 15,
    initials: 'KL',
    name: 'Kevin Lewis',
    tier: 'Bronze',
    orders: 165,
    points: 1980,
    trend: 'down',
  },
];
