import {
  Zap,
  Target,
  Award,
  Star,
  TrendingUp,
  Users,
  Moon,
  Activity,
  Package,
  Heart,
} from 'lucide-react';
import DemonIcon from '@/assets/images/icons/badgeIcon-2.png';
import PerfectWeekIcon from '@/assets/images/icons/badgeIcon-1.png';
import CenturyClubIcon from '@/assets/images/icons/percentIcon.png';
import RisingStarIcon from '@/assets/images/icons/badgeIcon-4.png';
import { type Badge } from './types';

export const badges: Badge[] = [
  {
    id: '1',
    name: 'Speed Demon',
    description: 'Complete 50 deliveries with 100% on-time rate',
    icon: Zap,
    iconBg: 'bg-blueGreenGradient',
    iconColor: 'text-white',
    rarity: 'Rare',
    earned: true,
    earnedDate: '2024-12-10',
    iconImage: DemonIcon,
  },
  {
    id: '2',
    name: 'Perfect Week',
    description: 'Maintain 100% completion rate for 7 consecutive days',
    icon: Target,
    iconBg: 'bg-bluePurpleGradient',
    iconColor: 'text-white',
    rarity: 'Epic',
    earned: true,
    earnedDate: '2024-12-05',
    iconImage: PerfectWeekIcon,
  },
  {
    id: '3',
    name: 'Century Club',
    description: 'Complete 100 total deliveries',
    icon: Award,
    iconBg: 'bg-grayDarkGradient border border-[#9CA3AF]',
    iconColor: 'text-white',
    rarity: 'Common',
    earned: true,
    earnedDate: '2024-11-28',
    iconImage: CenturyClubIcon,
  },
  {
    id: '4',
    name: 'Rising Star',
    description: 'Reach Silver tier',
    icon: Star,
    iconBg: 'bg-blueGreenGradient',
    iconColor: 'text-white',
    rarity: 'Rare',
    earned: true,
    earnedDate: '2024-12-01',
    iconImage: RisingStarIcon,
  },
  {
    id: '5',
    name: 'Top 10',
    description: 'Reach top 10 on the leaderboard',
    icon: TrendingUp,
    iconBg: 'bg-[#F3F4F6] border border-[#E5E7EB]',
    iconColor: 'text-white',
    rarity: 'Epic',
    earned: false,
    progress: { current: 12, target: 10 },
  },
  {
    id: '6',
    name: 'Golden Touch',
    description: 'Reach Gold tier',
    icon: Award,
    iconBg: 'bg-[#F3F4F6] border border-[#E5E7EB]',
    iconColor: 'text-white',
    rarity: 'Legendary',
    earned: false,
    progress: { current: 2450, target: 5000 },
  },
  {
    id: '7',
    name: 'Streak Master',
    description: 'Complete deliveries for 30 consecutive days',
    icon: Activity,
    iconBg: 'bg-[#F3F4F6] border border-[#E5E7EB]',
    iconColor: 'text-white',
    rarity: 'Epic',
    earned: false,
    progress: { current: 14, target: 30 },
  },
  {
    id: '8',
    name: 'Team Player',
    description: 'Help 10 new drivers with their first delivery',
    icon: Users,
    iconBg: 'bg-[#F3F4F6] border border-[#E5E7EB]',
    iconColor: 'text-white',
    rarity: 'Rare',
    earned: false,
    progress: { current: 3, target: 10 },
  },
  {
    id: '9',
    name: 'Night Owl',
    description: 'Complete 25 deliveries after 10 PM',
    icon: Moon,
    iconBg: 'bg-[#F3F4F6] border border-[#E5E7EB]',
    iconColor: 'text-white',
    rarity: 'Rare',
    earned: false,
    progress: { current: 8, target: 25 },
  },
  {
    id: '10',
    name: 'Marathon Runner',
    description: 'Complete 50 deliveries in a single day',
    icon: Activity,
    iconBg: 'bg-[#F3F4F6] border border-[#E5E7EB]',
    iconColor: 'text-white',
    rarity: 'Legendary',
    earned: false,
    progress: { current: 15, target: 50 },
  },
  {
    id: '11',
    name: 'Five Hundred Club',
    description: 'Complete 500 total deliveries',
    icon: Package,
    iconBg: 'bg-[#F3F4F6] border border-[#E5E7EB]',
    iconColor: 'text-white',
    rarity: 'Epic',
    earned: false,
    progress: { current: 234, target: 500 },
  },
  {
    id: '12',
    name: 'Customer Favorite',
    description: 'Receive 100 five-star ratings',
    icon: Heart,
    iconBg: 'bg-[#F3F4F6] border border-[#E5E7EB]',
    iconColor: 'text-white',
    rarity: 'Rare',
    earned: false,
    progress: { current: 67, target: 100 },
  },
];
